### ISSUE TITLE
Preflight Checklist Additions

### ISSUE THREAD

**Issue by OccultSlolem** [Team4159/FRC-2023#14]
The following are additions we added to the prematch checklist during SFR:

- Check PDH for sticky faults.
- Check that the correct code is deployed.
- Check that no wires are connected to the robot and DS laptop.
- Check wheels for carpet fabric.
- Check for bad wire connections.

We should review these changes and make sure appropriate changes are made to the permanent preflight checklist.

**Comment by Mayamelon** [comment]
added to checklist
